apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: primary
        image: dummy
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs
spec:
  rules:
  - host: nodejs
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nodejs
            port:
              number: 80
