apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  template:
    spec:
      containers:
      - name: primary
        env:
        - name: COLOR
          value: green
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs
spec:
  rules:
  - host: nodejs-prod.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nodejs-green
            port:
              number: 80
